package: demo_community
version: 4.0.2
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/demo_community'
page:
    title: 'translate:demo_community_title'
    perm: 'demo_community[]'
    pjax: true
    subpages:
        install: { title: 'translate:title' }

requires:
    packages:
        # Important: require system addOns only! Find other addOns required in `package.setup.yml`.
        # This is because we want the demo to be installed in first place without the need to install
        # any other addOns beforehand. The demo comes with a setup feature which checks the
        # `package.setup.yml` file where all additional addOns are defined. It will download and
        # install these addOns seamlessly for you once you’ve clicked the setup button.
        # After setup, both package files get merged. Be sure to not publish a merged `package.yml`
        # with your new release. Always use the original un-merged file!
        backup: '>=2.5.1'
        structure/content: '>=2.9.0'
    redaxo: '>=5.9.0'
    php:
        version: '>=7.4, <8.3'

console_commands:
    'demo_community:install': rex_command_demo_community_install
    'demo_community:dump_files': rex_command_demo_community_dumpfiles
    'demo_community:dump_tables': rex_command_demo_community_dumptables
