package: demo_community
version: '2.1.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/demo_community

page:
    title: 'Community-Demo'
    perm: demo_community[]
    pjax: true
    subpages:
        install: { title: 'translate:title' }

requires:
    packages:
        backup: '>=2.0.3'
        structure/content: '>=2.1.0'
    redaxo: '>=5.2.0'
